apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APPLICATION_NAME
  namespace: $APPLICATION_ENVIRONMENT
  labels:
    app: $APPLICATION_NAME
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: $APPLICATION_NAME
  template:
    metadata:
      labels:
        app: $APPLICATION_NAME
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
    spec:
      containers:
        - name: $APPLICATION_NAME
          image: $CONTAINER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: IGN_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: $KUBERNETES_CONFIG_MAP
      nodeSelector:
        server: "true"
